old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        new_user:
            connection: default
            class: Authentication\Infrastructure\Domain\Messages\NewUserCreatedEvent
            exchange_options:
                name: 'new_user'
                type: 'fanout'
        ban_user:
            connection: default
            exchange_options:
                name: 'ban_user'
                type: 'fanout'
#    consumers:
#        new_user:
#            connection:       default
#            exchange_options: {name: 'new_user', type: fanout}
#            queue_options:    {name: 'new_user'}
#            callback:         Authentication\Application\Service\User\CreateUserService


