old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        new_user:
            connection: default
            exchange_options:
                name: 'new_user_exchange'
                type: 'fanout'
        ban_user:
            connection: default
            exchange_options:
                name: 'ban_user_exchange'
                type: 'fanout'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
