security:
    encoders:
        Authentication\Domain\Entity\User\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: Authentication\Domain\Entity\User\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            anonymous: true
            context: user
            stateless: true
            pattern: ^/api/user
            guard:
                authenticators:
                    - Authentication\Infrastructure\Domain\Authenticators\UserApiAuthenticatorService
                    - Authentication\Infrastructure\Domain\Authenticators\UserCredentialsAuthenticatorService
                entry_point: Authentication\Infrastructure\Domain\Authenticators\UserApiAuthenticatorService
        client:
            anonymous: true
            context: user
            stateless: true
            pattern: ^/api/client
            guard:
                authenticators:
                    - Authentication\Infrastructure\Domain\Authenticators\ClientApiAuthenticatorService
                    - Authentication\Infrastructure\Domain\Authenticators\UserCredentialsAuthenticatorService
                entry_point: Authentication\Infrastructure\Domain\Authenticators\ClientApiAuthenticatorService

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
