Authentication\Domain\Entity\User\User:
  type: entity
  table: Users
  repositoryClass: Authentication\Infrastructure\Repositories\User\UserRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    username:
      type: string
      length: 10
      nullable: true
      unique: true
    email:
      type: string
      unique: true
      length: 30
    createdAt:
      type: datetime
    password:
      type: string

  oneToMany:
    accessTokens:
      targetEntity: Authentication\Domain\Entity\User\AccessToken
      mappedBy: user
      cascade: ["persist", "merge", "remove"]

  manyToMany:
    roles:
      targetEntity: Authentication\Domain\Entity\Role
      mappedBy: users
