Authentication\Domain\Entity\Client\Client:
  type: entity
  table: Clients
  repositoryClass: Authentication\Infrastructure\Repositories\Client\ClientRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  oneToMany:
    accessTokens:
      targetEntity: Authentication\Domain\Entity\Client\AccessToken
      mappedBy: client
      cascade: ["persist", "merge", "remove"]
  manyToMany:
    roles:
      targetEntity: Authentication\Domain\Entity\Role
      mappedBy: clients
  fields:
    name:
      type: string

    ip:
      type: string
