Authentication\Domain\Entity\Values\Setting:
  type: entity
  table: Settings
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  manyToOne:
    user:
      targetEntity: Authentication\Domain\Entity\User
      inversedBy: settings
    client: 
      targetEntity: Authentication\Domain\Entity\Client

  fields:
    name:
      type: string
    type:
      type: string
    value:
      type: string